dsn: sqlserver://admin:KJCIjbjfnDAUpwg6Twqy@database-1.cxnxagsqunz0.us-east-1.rds.amazonaws.com:1433/information_schema
metrics:
  db_table_size_bikes:
    query: 
      "USE BikeStores; SELECT t.NAME AS tablename,	CAST(ROUND(((SUM(a.total_pages) * 8) / 1024.00), 2) AS NUMERIC(36, 2)) AS totalspacemb, 
      CAST(ROUND(((SUM(a.total_pages) - SUM(a.used_pages)) * 8) / 1024.00, 2) AS NUMERIC(36, 2)) AS unusedspacemb FROM sys.tables t 
      INNER JOIN sys.indexes i ON t.OBJECT_ID = i.object_id INNER JOIN sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id 
      INNER JOIN sys.allocation_units a ON p.partition_id = a.container_id LEFT OUTER JOIN sys.schemas s ON t.schema_id = s.schema_id 
      WHERE t.NAME NOT LIKE 'dt*' AND t.is_ms_shipped = 0 AND i.OBJECT_ID > 255 GROUP BY t.Name, s.Name, p.Rows ORDER BY TotalSpaceMB DESC, t.Name"
    type: gauge
    description: "process count by host"
    labels: ["user","host"]
    value: sessions
  db_table_size_bikes2:
    query: 
      "USE BikeStores2; SELECT t.NAME AS tablename,	CAST(ROUND(((SUM(a.total_pages) * 8) / 1024.00), 2) AS NUMERIC(36, 2)) AS totalspacemb, 
      CAST(ROUND(((SUM(a.total_pages) - SUM(a.used_pages)) * 8) / 1024.00, 2) AS NUMERIC(36, 2)) AS unusedspacemb FROM sys.tables t 
      INNER JOIN sys.indexes i ON t.OBJECT_ID = i.object_id INNER JOIN sys.partitions p ON i.object_id = p.OBJECT_ID AND i.index_id = p.index_id 
      INNER JOIN sys.allocation_units a ON p.partition_id = a.container_id LEFT OUTER JOIN sys.schemas s ON t.schema_id = s.schema_id 
      WHERE t.NAME NOT LIKE 'dt*' AND t.is_ms_shipped = 0 AND i.OBJECT_ID > 255 GROUP BY t.Name, s.Name, p.Rows ORDER BY TotalSpaceMB DESC, t.Name"
    type: gauge
    description: "process count by host"
    labels: ["user","host"]
    value: sessions
